### PR TITLE
Add Linux version (or compatibility change)

### PR DESCRIPTION
**Pull request by LoanSpac**
When I saw the video, I wanted the same thing but I'm using Linux. So I edited the script for run on Linux.

### CODE REVIEW

**Comment by quasar098** [comment]
very good, although for the linux version there is still the code for the transparent using the win32api, win32con which is not supported on linux, so i think the linux version may not support transparent window currently but that is ok

looking at this more soon

**Comment by LoanSpac** [comment]
I can create a update ?
I have an idea for simplify the usage and automatically detect the os (for the loose message for example : if is windows -> "delete C:/System32", if is linux -> "delete /root")

**Comment by LoanSpac** [comment]
Sorry, I will remade it better
I have pull too fast

**Comment by LoanSpac** [comment]
It's fine now
I have finish all changes

**Comment by quasar098** [comment]
i will hopefully have time to look at this soon

**Comment by quasar098** [comment]
changed a few things up it should be good now

**Comment by quasar098** [comment]
also what distro are you using ? want to know to add it to the readme that it works on this distro

**Pull request merged**
