### PR TITLE
A bugfix

### PR DESCRIPTION
**Pull request by HHonzik**
Fixes spawn-all.py to run the server also and uses a different less used and protected port, added instruction how to install

### CODE REVIEW

**Comment by quasar098** [comment]
will look at this soon

**Comment by quasar098** [comment]
not accepting this there are a few things i dont like

**Comment by quasar098** [comment]
i will add in the install instruction eventually if this is not fixed though

**Comment by HHonzik** [comment]
> not accepting this there are a few things i dont like

Like what?

**Comment by quasar098** [comment]
first of all, changing the system command from python3 to python may cause issues for people who have a very messed up python environment. a generalizable fix is preferred. 
additionally, you added config.json when it is clearly in the .gitignore
what would be preferable is making the config.json automatically create if it doesn't exist.
also, i don't like spawning the server in spawn-all.py because it may lead to lots of error and bug reports when the cause is having the port be occupied from running the spawn-all twice.
finally, i will get a lot of youtube comments and complaints that people don't know how to run it even with instructions because these instructions are too vague

**Pull request closed without merging**
