### PR TITLE
Mainly QoL stuff.

### PR DESCRIPTION
**Pull request by HHonzik**
Just some stuff to mainly improve setup and making the config more usefull.

### CODE REVIEW

**Comment by quasar098** [comment]
ill check this out soon

**Comment by quasar098** [comment]
i am not a huge fan of the removal of config.json from the .gitignore because i change my settings all the time and that will lead to a lot of people complaining that it doesn't look the same

**Comment by HHonzik** [comment]
ok, i will remove it

**Comment by HHonzik** [comment]
also updated the README for instructions how to change the config.

**Comment by HHonzik** [comment]
Added a setting for making the seed 0xF0C_5 to make the key actually random

**Comment by quasar098** [comment]
two typos/misspellings in the readme

also the "If you do not going to run this anymore, press CTRL+C to close this" message might get annoying

**Comment by HHonzik** [comment]
Fixed that.

**Comment by quasar098** [comment]
i feel like the issue with a cheats mode is that people will get bored, it is known that in general, adding cheats to a game makes the audience go away because why even bother if you can turn on cheats, so i think that goes against the core of the game

**Comment by HHonzik** [comment]
like its off by default and the config is optional to use or tweak.mainly with the seed focus it you find what it is once, its that always beacuse it doesnt seem to change when its played again, so basically adding the option for the seed focus is kinda a reverse of that, the keys do change when you just relaunch the clients but not the server, but still with the seed focus its not random, with that tweak,still by just removing it from the config so it would be more hidden

**Comment by quasar098** [comment]
major merge conflicts rn, also i changed the source to use 2 random bytes which makes the 0xFOC_5 key stay the same issue fixed

**Pull request closed without merging**
